<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Multiplayer_Shuttle_Dock_Patch</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>12</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Publicizer" Version="2.3.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.4871" />
    <PackageReference Include="Lib.Harmony" Version="2.4.2" />
    <PackageReference Include="RimWorld.MultiplayerAPI" Version="0.6.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="References\*.dll">
      <Private>false</Private>
    </Reference>
  </ItemGroup>
  
  <ItemGroup>
	<Publicize Include="Assembly-CSharp;0Harmony" />
  </ItemGroup>
</Project>
